// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go_micro/controller"
	"go_micro/model"
	"go_micro/service"
)

// Injectors from wire.go:

func InitializeRouter() *Router {
	modelModel := model.NewModel()
	serviceService := service.NewService(modelModel)
	controllerController := controller.NewController(serviceService)
	router := NewRouter(controllerController)
	return router
}
