// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"go_micro/controller"
	"go_micro/service"
)

// Injectors from wire.go:

func InitializeRouter() Router {
	mockDB := service.NewMockDB()
	serviceService := service.NewService(mockDB)
	controllerController := controller.NewController(serviceService)
	engine := gin.Default()
	mainRouter := NewRouter(controllerController, engine)
	return mainRouter
}
