// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "go_mvc/model"

	mock "github.com/stretchr/testify/mock"
)

// Model is an autogenerated mock type for the Model type
type Model struct {
	mock.Mock
}

// ModelUser provides a mock function with given fields: dbRecord
func (_m *Model) ModelUser(dbRecord model.DataBaseUser) model.User {
	ret := _m.Called(dbRecord)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(model.DataBaseUser) model.User); ok {
		r0 = rf(dbRecord)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	return r0
}
