// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "go_micro/model"

	mock "github.com/stretchr/testify/mock"
)

// Model is an autogenerated mock type for the Model type
type Model struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: id
func (_m *Model) GetUser(id int64) model.User {
	ret := _m.Called(id)

	var r0 model.User
	if rf, ok := ret.Get(0).(func(int64) model.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	return r0
}
